CREATE DATABASE SHOPPINGCENTER
USE SHOPPINGCENTER

CREATE TABLE BRANDS(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(50)
)
INSERT INTO BRANDS
VALUES ('ZARA')

CREATE TABLE GENDERS(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(50)
)
INSERT INTO GENDERS
VALUES ('MALE') 
INSERT INTO GENDERS
VALUES ('FEMALE') 


CREATE TABLE PRODUCTS(
ID INT PRIMARY KEY IDENTITY,
MODEL NVARCHAR(50),
IMAGE NVARCHAR(100),
BRANDID INT REFERENCES BRANDS(ID),
GENDERID INT REFERENCES GENDERS(ID)
)
INSERT INTO PRODUCTS
VALUES ('A','I',1,2) 

SELECT B.ID,B.NAME,(SELECT COUNT(P.ID) FROM PRODUCTS  AS P WHERE B.ID=P.BRANDID) 'COUNT OF PRODUCTS'  FROM BRANDS AS B

